services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    entrypoint: >
      /bin/sh -c "
      minio server --console-address ':9001' /data &
      sleep 5;
      until curl -s http://localhost:9000/minio/health/live; do sleep 1; done;
      mc alias set local http://localhost:9000 minioadmin minioadmin;
      mc mb local/binx || true;
      wait
      "

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: binx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  postgres_data:
